#!/usr/bin/env bash

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

## Step 1: Force apt update
apt-get update --allow-releaseinfo-change

## Step 2: Make sure 'git' is installed!
check_install_pkgs git

## Step 3: Move to Home Dir as WorkingDirectoy
pushd "/home/pi"

## Step 4: clone KIAUH repo
echo_green "Clone pi-Stomp repository ..."
git clone -b beta https://github.com/TreeFallSound/pi-stomp.git

unpack /filesystem/home/pi /home/"pi" "pi"

popd
