#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap
check_install_pkgs git

pushd $(mktemp -d) && git clone https://github.com/micahvdm/jack2.git
pushd jack2
./waf configure
./waf build
sudo ./waf install
popd

pushd $(mktemp -d) && git clone https://github.com/micahvdm/browsepy.git
pushd browsepy
sudo pip3 install ./
popd

pushd $(mktemp -d) && git clone https://github.com/micahvdm/mod-host.git
pushd mod-host
make
sudo make install
popd

pushd $(mktemp -d) && git clone https://github.com/micahvdm/mod-ui.git
pushd mod-ui
chmod +x setup.py
cd utils
make
cd ..
sudo ./setup.py install
cp -r default.pedalboard /home/pi/data/.pedalboards
popd

pushd $(mktemp -d) && git clone https://github.com/micahvdm/mod-midi-merger.git
pushd mod-midi-merger
mkdir build && cd build
cmake ..
make
sudo make install
popd

pushd $(mktemp -d) && git clone https://github.com/BlokasLabs/amidithru.git
pushd amidithru
sed -i 's/CXX=g++.*/CXX=g++/' Makefile
sudo make install
popd

pushd $(mktemp -d) && git clone https://github.com/micahvdm/touchosc2midi.git
pushd touchosc2midi
sudo pip3 install ./
popd

sudo adduser --no-create-home --system --group jack
sudo adduser pi jack --quiet
sudo adduser root jack --quiet
sudo adduser jack audio --quiet