#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

gitclone JACK_REPO jack2

pushd "/home/pi/jack2"
./waf configure
./waf build
sudo ./waf install
popd

gitclone BROWSEPY_REPO browsepy

pushd "/home/pi/browsepy"
sudo pip3 install ./
popd

gitclone MODHOST_REPO mod-host

pushd "/home/pi/mod-host"
make
sudo make install
popd

gitclone MODUI_REPO mod-ui

pushd "/home/pi/mod-ui"
chmod +x setup.py
cd utils
make
cd ..
sudo ./setup.py install
cp -r default.pedalboard /home/pi/data/.pedalboards
popd

gitclone MODMIDI_REPO mod-midi-merger

pushd "/home/pi/mod-midi-merger"
mkdir build && cd build
cmake ..
make
sudo make install
popd

gitclone AMIDI_REPO amidithru

pushd "/home/pi/amidithru"
sed -i 's/CXX=g++.*/CXX=g++/' Makefile
sudo make install
popd

gitclone TOUCHOSC_REPO touchosc2midi

pushd "/home/pi/touchosc2midi"
sudo pip3 install ./
popd

sudo adduser --no-create-home --system --group jack
sudo adduser pi jack --quiet
sudo adduser root jack --quiet
sudo adduser jack audio --quiet