#!/usr/bin/env bash
# CustomPiOS auto-mount-removable media module
# Script sets that devices would be automatically mounted to /media
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########
set -x
set -e

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

wget https://github.com/kdoren/linux/releases/download/rpi_6.1.54-rt15/linux-image-6.1.54-rt15-v8+_6.1.54-1_arm64.deb
wget https://github.com/kdoren/linux/releases/download/rpi_6.1.54-rt15/linux-libc-dev_6.1.54-1_arm64.deb
wget https://github.com/kdoren/linux/releases/download/rpi_6.1.54-rt15/linux-headers-6.1.54-rt15-v8+_6.1.54-1_arm64.deb

dpkg -i *.deb

KERN=6.1.54-rt15-v8+
mkdir -p /boot/$KERN/overlays/
cp -d /usr/lib/linux-image-$KERN/overlays/* /boot/$KERN/overlays/
cp -dr /usr/lib/linux-image-$KERN/* /boot/$KERN/
touch /boot/$KERN/overlays/README
mv /boot/vmlinuz-$KERN /boot/$KERN/
mv /boot/System.map-$KERN /boot/$KERN/
cp /boot/config-$KERN /boot/$KERN/
cat >> /boot/config.txt << EOF

[all]
kernel=vmlinuz-$KERN
# initramfs initrd.img-$KERN
os_prefix=$KERN/
overlay_prefix=o/
[all]
EOF

rm -v *.deb