#!/usr/bin/env bash

# shellcheck enable=requires-variable-braces

# Error handling
set -Ee

# shellcheck disable=SC1091
source /common.sh
install_cleanup_trap

wget https://www.treefallsound.com/downloads/lv2plugins.tar.gz
tar -zxf lv2plugins.tar.gz
rm lv2plugins.tar.gz

git clone https://github.com/TreeFallSound/pi-stomp-pedalboards.git /home/pi/data/.pedalboards/

