#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

pushd $(mktemp -d) && git clone https://github.com/moddevices/mod-ttymidi.git
pushd mod-ttymidi
sudo make install

popd